### PR TITLE
Fixed UnicodeEncodeError at categories admin

### PR DESCRIPTION
**Pull request by flaiming**
I fixed the issue #123 by marking format pattern string as Unicode explicitly.

### CODE REVIEW

**Comment by epicserve** [comment]
Unfortunately, I'm pretty sure your approach won't work with Python 3.

**Comment by flaiming** [comment]
@epicserve Why not?

**Comment by epicserve** [comment]
@flaiming Try this branch https://github.com/callowayproject/django-categories/tree/admin-unicode-fix. If it fixes the issue I'll merge it in and make a release.

**Comment by flaiming** [comment]
@epicserve Yup, that fixed it.

**Comment by epicserve** [comment]
@flaiming thank you for pointing me in the right direction! I'm going to close this since you said it's been fixed now.

**Comment by flaiming** [comment]
@epicserve Thanks, you are welcome :)

**Pull request closed without merging**
