### PR TITLE
Avoid the "Cannot call get_descendants on unsaved Category instances" ValueError

### PR DESCRIPTION
**Pull request by msaelices**
When adding categories in admin interface.

### CODE REVIEW

**Comment by bhappyz** [comment]
Can we get merged I am facing similar issue

**Comment by martin-c** [comment]
Works for me as well, I hope this gets integrated soon.

**Comment by bhappyz** [comment]
Any body ?

**Comment by felixSchl** [comment]
Works for me, too. Can this get merged?

**Comment by epicserve** [comment]
@msaelices, @felixSchl, tests aren't passing. I'm happy to look at this once the tests pass. :)

**Comment by felixSchl** [comment]
@epicserve fair enough, but is this not pretty fundamental to the project that one can add categories from the admin interface? Are there tests that confirm you can create them from the admin? I am saying this in hope to motivate development on a core contributor's end since it will take longer (for me at least) to get up to speed and contribute a fix. I am also very tight on time currently and for the foreseeable future.

**Comment by epicserve** [comment]
This should be resolved now. I added tests to cover the admin as well. @msaelices, I had to cherry-pick your commits because your branch wasn't up to date. Thank you for your contribution.

**Comment by felixSchl** [comment]
@epicserve epic :+1:

**Pull request closed without merging**
