### PR TITLE
Django 1.8

### LINKED ISSUE #91: Django 1.8 Support
There is RemovedInDjango19Warning deprecation warning that needs handled when using Django 1.8.

### PR DESCRIPTION
**Pull request by epicserve**
This resolves #91

### CODE REVIEW

**Comment by dimetris** [comment]
+1

**Comment by miceno** [comment]
Hi @epicserve 

Great to have the changes for Django 1.8.

Running the code of the patch makes the application break with an error:

`'category_tags' is not a valid tag library: ImportError raised loading categories.templatetags.category_tags: cannot import name FilterExpression`

I guess the issue is that Django 1.8 changed the template system and move the code to a new namespace. I tried to substitute imports from `django.template` to `django.template.base` and it solve the problem.

**Comment by epicserve** [comment]
@miceno interesting ... I'm not using any of the category tags, unless the admin view uses them and if it does, that view is working fine. Anyway, I haven't ran into that issue yet.

**Comment by epicserve** [comment]
The current master branch supports 1.8

**Pull request closed without merging**
